version: "#{build}"
os: Visual Studio 2015
configuration: Release

environment:
  matrix:
    - FRAMEWORK: netcoreapp1.0
      LIBFRAMEWORK: netstandard1.6
    - FRAMEWORK: netcoreapp1.0
      LIBFRAMEWORK: netstandard1.5
    - FRAMEWORK: net45
      LIBFRAMEWORK: net45

before_build:
- ps: dotnet --info
- ps: dotnet restore --verbosity detailed

build_script:
- ps: dotnet build -c $env:CONFIGURATION -f $env:LIBFRAMEWORK src/Virtlink.Utilib/
- ps: dotnet build -c $env:CONFIGURATION -f $env:FRAMEWORK test/Virtlink.Utilib.Tests/

test_script:
- ps: dotnet test -c $env:CONFIGURATION -f $env:FRAMEWORK ./test/Virtlink.Utilib.Tests

after_test:
- ps: dotnet pack -c $env:CONFIGURATION src/Virtlink.Utilib/

artifacts:
- path: 'src/Virtlink.Utilib/bin/Release/*.nupkg'
  name: NuGet Packages

deploy:
- provider: GitHub
  description: ""
  auth_token:
    secure: gxD+NTodnQNMMljEkLwbmfQdsyBZFRIioVMM+RQSFD3+h1GEgsEGuINxcfNgVceY
  artifact: /.*\.nupkg/
  draft: true
  prerelease: true
  on:
    branch: master
    appveyor_repo_tag: true
- provider: NuGet
  api_key:
    secure: 80Ifo8pBjEsFrG2mn50qSl7+uFgquQSareLS3l21DfWT49nFtb/SZsHSkR/DRDsO
  skip_symbols: true
  artifact: /.*\.nupkg/
  on:
    branch: master
    appveyor_repo_tag: true
